# Generated by Django 3.1.2 on 2020-12-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150, verbose_name='Question')),
                ('item1', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='pics')),
                ('item2', models.CharField(max_length=100)),
                ('img2', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
