# Generated by Django 3.1.2 on 2021-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_poll',
            name='category',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
