# Generated by Django 3.1.2 on 2021-01-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_create_poll_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_poll',
            name='img3',
            field=models.ImageField(default='', upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='img4',
            field=models.ImageField(default='', upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='item3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='item4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
