# Generated by Django 3.1.2 on 2021-01-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210112_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_poll',
            name='count1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='count2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='count3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='count4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
