# Generated by Django 3.1.2 on 2021-01-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210114_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_poll',
            name='percent1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='percent2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='percent3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='percent4',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_poll',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
